### PR TITLE
Fix database ID and CI failure on RHEL

### PR DESCRIPTION
**Pull request by bmhughes**
# Description

Fix database ID and CI failure on RHEL

## Issues Resolved

- n/a

## Check List

- [x] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by damacus** [comment]
Should we just add the prepare step to the install recipe? Or should we document that the user needs to enable that repo?

**Comment by bmhughes** [comment]
Hmm I think you're right, it's only needed if for the devel package but we already install epel and scl so it's probably a better option.

**Comment by damacus** [comment]
Either way. thanks for doing this!

**Comment by kitchen-porter** [comment]
Released as: [11.2.1](https://github.com/sous-chefs/postgresql/releases/tag/11.2.1)

**Pull request merged**
