### PR TITLE
Escape username

### PR DESCRIPTION
**Pull request by asasmoyo**
### Description

Escape username so we can use username with dash

### Issues Resolved

Closes: https://github.com/sous-chefs/postgresql/issues/583

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/line-cookbook/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Xorima** [comment]
Could you add a test in for this as well please?

**Comment by asasmoyo** [comment]
Please check again. I've added the test but I'm not sure I placed correctly

**Comment by damacus** [comment]
That looks good to me! 

Could you fix the CHANGELOG and I'll merge & release. 


Thanks for the contribution!

**Comment by damacus** [comment]
Approved pending checks :)

**Comment by damacus** [comment]
Released as 7.1.3. 

Thanks!

**Pull request merged**
