### PR TITLE
make postgres.conf world readable

### LINKED ISSUE #588: Mode 600 is restrictive
The setting of the postgres.conf mode to 600 makes it not readable by the psql client.
`Error: Invalid data directory for cluster 9.6 main` is what I get when running psql as a normal user
strace shows 
```
open("/usr/lib/postgresql/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 4
open("/etc/postgresql/9.6/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 4
open("/etc/postgresql/9.6/main/postgresql.conf", O_RDONLY) = -1 EACCES (Permission denied)
open("/var/lib/postgresql/9.6/main/postgresql.auto.conf", O_RDONLY) = -1 EACCES (Permission denied)
open("/etc/postgresql/9.6/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 4
open("/etc/postgresql/9.6/main/postgresql.conf", O_RDONLY) = -1 EACCES (Permission denied)
open("/var/lib/postgresql/9.6/main/postgresql.auto.conf", O_RDONLY) = -1 EACCES (Permission denied)
open("/etc/postgresql/9.6/main/postgresql.conf", O_RDONLY) = -1 EACCES (Permission denied)
open("/var/lib/postgresql/9.6/main/postgresql.auto.conf", O_RDONLY) = -1 EACCES (Permission denied)
``` 
This is set in the file
https://github.com/sous-chefs/postgresql/blob/38915d62d922374bbc4d2363306d8ac1cd81baaf/resources/server_conf.rb#L37

Best practices state:
`All the conf files should be owned by the postgres user, and the configuration files should be world-readable if possible (indeed, it’s a requirement for Debian based system that postgresql.conf be readable for psql to work!).`
https://www.endpoint.com/blog/2010/09/27/postgres-configuration-best-practices

I would suggest a 644

### PR DESCRIPTION
**Pull request by jmikedupont2**
### Description

Allows users to access postgres with psql locally

### Issues Resolved

#588 

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by damacus** [comment]
Thanks for the link to the best practises, or at least "it should work this way" documentation, this made this PR such much easier to merge in!

**Comment by damacus** [comment]
This has been released to the supermarket, thanks! 

https://twitter.com/souschefsorg/status/1081944936671526913

**Comment by jmikedupont2** [comment]
Awsome

**Comment by JohnRoesler** [comment]
I agree with Dan. Very easy to review. Thank you for the clear definition of 'why'!

**Pull request merged**
