### PR TITLE
Feature/ident resource

### LINKED ISSUE #284: Feature request: Config options for pg_ident.conf
Add a new node config attribute, `node['postgresql']['pg_ident']` which behaves like `node['postgresql']['pg_hba']`, but for the `pg_ident.conf` file instead of the `pg_hba.conf` file.

See [the PostgreSQL documentation page on this topic](http://www.postgresql.org/docs/9.4/static/auth-username-maps.html) for more information.

Suggested format:

```ruby
node['postgresql']['pg_ident'] = {
  map_name => [
    [system_username, pg_username],
    [system_username, pg_username],
    [system_username, pg_username],
  ],
  map_name => [
    [system_username, pg_username],
    [system_username, pg_username],
    [system_username, pg_username],
  ],
}
```

Or perhaps:

node['postgresql']['pg_ident'] = {
  map_name => {
    system_username => [pg_username, pg_username],
    system_username => [pg_username],
  },
  map_name => {
    system_username => [pg_username, pg_username],
    system_username => [pg_username],
  },
}

Or alternately:

```ruby
node['postgresql']['pg_ident'] = [
  {map_name: map_name, system_username: system_username, pg_username: pg_username},
  {map_name: map_name, system_username: system_username, pg_username: pg_username},
  {map_name: map_name, system_username: system_username, pg_username: pg_username},
}
```

Any of those formats would be fine with me.

### PR DESCRIPTION
**Pull request by YpNo**
### Description

Create Ident resource + Few Fixes

### Issues Resolved

#284 

### Contribution Check List

- [x] Tested on Debian 7 and CentOS 6
- [ ] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by damacus** [comment]
Looks like your editor is adding in random crap at the end of lines or your branch needs updating? As it's trying to revert a bunch of README work @martinisoft did last night :(

**Comment by YpNo** [comment]
it's me. Sometime with Markdown editor/reader (like mkdocs), we need to add three space at the end of line to make return line. Don't need in Github ?

**Comment by martinisoft** [comment]
Can you rebase this against the current master? It looks like you accidentally merged in some of my doc updates into your PR.

**Comment by YpNo** [comment]
Hi @martinisoft, I am up-to-date with master. I have just fix some tab indent in tables

**Pull request merged**
