### PR TITLE
[GH-683] Don't leak users password

### PR DESCRIPTION
**Pull request by hamarituc**
* Prevent leaking the users password during account creation

Signed-off-by: Mario Haustein <mario.haustein@hrz.tu-chemnitz.de>

# Description

Prevent leaking the users password during account creation.

## Issues Resolved

- GH-683

## Check List

- [x] All tests pass. See TESTING.md for details.
- [ ] ~~New functionality includes testing.~~ not applicable, bugfix
- [ ] ~~New functionality has been documented in the README if applicable.~~ not applicable, bugfix

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ramereth** [comment]
@hamarituc thanks for the pull request! Can you please add a changelog entry?

**Comment by hamarituc** [comment]
It seems the cookbook is not compatible to Chef 17. The checks passed successfully with Chef 15.17.4 (see CI Job 173) but failed with Chef 17.0.246 (see CI Job 175). How to proceed with this pull request? I have no clue how to fix the cookbook.

**Comment by ramereth** [comment]
> It seems the cookbook is not compatible to Chef 17. The checks passed successfully with Chef 15.17.4 (see CI Job 173) but failed with Chef 17.0.246 (see CI Job 175). How to proceed with this pull request? I have no clue how to fix the cookbook.

We're in the process of updating all of our cookbooks to properly work with Chef 17 so I recommend in the meantime to just hang tight until we get to this cookbook. Once that's done, then you can rebase and it should run again with new tests.

**Review by Xorima — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [9.0.1](https://github.com/sous-chefs/postgresql/releases/tag/9.0.1)

**Pull request merged**
