### PR TITLE
Unified mode for Chef 17 support

### PR DESCRIPTION
**Pull request by damacus**
# Description

Unified mode for Chef 17 support

## Check List

- [ ] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by damacus** [comment]
Marking as a major version as we're dropping support for Chef versions older than 15.3

**Comment by damacus** [comment]
As per https://github.com/chef/chef/issues/11496 systemd service detection is currently a little broken.

**Review by bmhughes — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [9.0.0](https://github.com/sous-chefs/postgresql/releases/tag/9.0.0)

**Pull request merged**
