### PR TITLE
Fix postgresql_access resource

### PR DESCRIPTION
**Pull request by scopenco**
### Description

`postgresql_access` is broken. No one resource manages pg_hba.conf except `postgresql_access` but it uses `edit_resource` to change nonexisting resource `template`. 

Please correct me where i'm wrong. Thanks.

### CODE REVIEW

**Comment by damacus** [comment]
Awesome @scopenco ! 

Could you throw in a config file test for this please?

**Comment by martinisoft** [comment]
I'm not sure how this is broken? Got a failing test? This is using the accumulator pattern which is still being fleshed out in Chef. I [wrote about this](https://blog.dnsimple.com/2017/10/chef-accumulators/) to explain the pattern so I'd love to see a failing case along with which Chef version you were running to hit this issue.

**Comment by damacus** [comment]
Closing this down as it doesn't look broken right now. 

Unless we can write some tests to prove this hypothesis wrong, this fixes a non-problem.

**Comment by martinisoft** [comment]
It's worth noting that Chef 13.7 [has a regression around node attributes](https://github.com/chef/chef/issues/6792) which completely screws up this pattern and is currently being addressed by Chef.

**Comment by damacus** [comment]
That bug affects haproxy and samba in that case too. But there's no point adding information to that ticket. Unless we can be constructive(!)

**Pull request closed without merging**
