### PR TITLE
Fix build and Documentation

### PR DESCRIPTION
**Pull request by YpNo**
### Description

  * Fix build on Debian 7 and Ubuntu 16.04 (force cluster stop with pg_cltcluster command and start it with init after)
  * Add resources documentation
  * Set minimal version of chef in .kitchen.yml for the builds
  * Update metadata

### Issues Resolved

Just build on Debian 7 and Ubuntu 16.04 + Enhancement

### Contribution Check List

- [x] All tests pass.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by YpNo** [comment]
Don't Merge, I try to fix all builds :)

**Comment by damacus** [comment]
Honestly, the #476 Pr is a corker, and I need rebase my stuff on that first. Doesn't look like I'm getting a chance today.

**Comment by YpNo** [comment]
Take your time :)
I found the issue for the builds. After template resource call in server_install, the service status check break down (use pg_lscluster -h) while the process really run (pg_ctlcluster 9.5 main status works). I will try to found a hint

**Comment by YpNo** [comment]
All green ✅  😄  \o/

**Pull request merged**
